export const category = {
  id: "c1",
  title: "Borse",
  slug: "borse",
  description: null,
  banners: [],
};
export const product = {
  id: "p1",
  slug: "borsa",
  title: "Borsa",
  shortDescription: null,
  description: null,
  images: ["/brand/logo.jpeg"],
  keywords: [],
  price: 20,
  discount: 0,
  stock: 1,
  isPhysical: true,
  isAvailable: true,
  isFeatured: true,
  kind: "HANDMADE",
  category: "BAG",
  status: "ACTIVE",
  fulfillmentMode: "READY",
  personalizationAllowed: false,
  publishedAt: "2026-01-01T00:00:00.000Z",
  brand: { id: "b1", title: "Mari", description: null, logo: null },
  categories: [category],
  productImages: [],
  options: [],
  variants: [
    {
      id: "v1",
      sku: "SKU",
      title: null,
      price: 25,
      compareAtPrice: null,
      active: true,
      leadTimeDays: null,
      inventory: {
        trackQuantity: true,
        quantityOnHand: 3,
        quantityReserved: 2,
        allowBackorder: false,
      },
      optionAssignments: [],
      bundleComponents: [],
    },
  ],
};
